function createfigure(zdata1)
%CREATEFIGURE(zdata1)
%  ZDATA1:  contour z

%  Auto-generated by MATLAB on 23-Apr-2025 10:45:28

% Create figure
figure1 = figure('WindowState','maximized');
colormap(jet);

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create contour
contour(zdata1,...
    'LevelList',[0 7.69230769230769 15.3846153846154 23.0769230769231 30.7692307692308 38.4615384615385 46.1538461538462 53.8461538461538 61.5384615384615 69.2307692307692 76.9230769230769 84.6153846153846 92.3076923076923]);

% Create ylabel
ylabel('y (m)');

% Create xlabel
xlabel('x (m)');

% Create title
title('2D Heat Conduction - Finite Volume Method');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[1 22]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[1 22]);
box(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'BoxStyle','full','Layer','top');
% Create colorbar
colorbar(axes1);

% Create textbox
annotation(figure1,'textbox',...
    [0.4306875 0.953586497890294 0.1068125 0.0337552742616033],...
    'String',{'\phi_{Top} =Phi_Top'},...
    'FitBoxToText','off');

